### ISSUE TITLE
Implement history chart

### ISSUE THREAD

**Issue by den-gts** [Alicelidel/banki_parcer#10]
Есть идея нарисовать график, как изменялся капитал банка со временем.
![img_20170816_095833_728](https://user-images.githubusercontent.com/3967080/29366878-dca5024e-82a3-11e7-8b47-869242753af4.jpg)
 
Если изменить месяц на странице с банками, то измениться URL. Можно множественными запросами узнать каков был капитал на интересный месяц.

График можно построить с помощью библиотек:
- [pygal](http://www.pygal.org/en/stable/) мне она больше всех нравиться. Но на windows очень сложно ее поставить.
- [plotly](https://plot.ly/python/line-charts/) - честно не пробовал, но выглядит красиво
- [mathplotlib](http://matplotlib.org) - олдскульный. Но с ним меньше всего проблем

**Comment by Alicelidel** [comment]
#11
